name: 'PureTropics coconut oil '
favicon: null
layout_spectrum: 0.609216800192371
typography_spectrum: 0.0427650329656899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43430553702637553
  lightness: 0.8964118505828083
  saturation: 0.18594634300097823
  rhythmicContrast: 0.9974115833174437
purpose: []
