name: PureTropics coconut oil
favicon: null
layout_spectrum: 0.02760316408239305
typography_spectrum: 0.39832458668388426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4255458815023303
  lightness: 0.9506599728483707
  saturation: 0.40230704890564084
  rhythmicContrast: 0.4559452736284584
purpose: []
