name: 'PureTropics coconut oil '
favicon: null
layout_spectrum: 0.7647134503349662
typography_spectrum: 0.7395108439959586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.13241504854522645
  lightness: 0.5607725742738694
  saturation: 0.8135044062510133
  rhythmicContrast: 0.09239650098606944
purpose: []
