name: PureTropics coconut oil
favicon: null
layout_spectrum: 0.3656613123603165
typography_spectrum: 0.5647663217969239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9303874594625086
  lightness: 0.8842216655611992
  saturation: 0.5440117644611746
  rhythmicContrast: 0.8745275130495429
purpose: []
