name: 'PureTropics coconut oil '
favicon: null
layout_spectrum: 0.6339421602897346
typography_spectrum: 0.21128639206290245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7718329287599772
  lightness: 0.5270183021202683
  saturation: 0.2334171668626368
  rhythmicContrast: 0.31542794429697096
purpose: []
