name: PureTropics coconut oil
favicon: null
layout_spectrum: 0.04127427190542221
typography_spectrum: 0.9416071828454733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.952617057133466
  lightness: 0.23565556132234633
  saturation: 0.14237769832834601
  rhythmicContrast: 0.49225927027873695
purpose: []
