name: 'PureTropics coconut oil '
favicon: null
layout_spectrum: 0.05591468745842576
typography_spectrum: 0.7376174866221845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3606120767071843
  lightness: 0.649768112692982
  saturation: 0.2566678577568382
  rhythmicContrast: 0.9983741492033005
purpose: []
