name: 'PureTropics coconut oil '
favicon: null
layout_spectrum: 0.546245560515672
typography_spectrum: 0.46124370070174336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.43972168443724513
  lightness: 0.9955741206649691
  saturation: 0.9848508632276207
  rhythmicContrast: 0.4054892580024898
purpose: []
