name: PureTropics coconut oil
favicon: null
layout_spectrum: 0.9197377183008939
typography_spectrum: 0.36152884527109563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.42998771858401597
  lightness: 0.07815227867104113
  saturation: 0.9768395309802145
  rhythmicContrast: 0.7671693360898644
purpose: []
